#!/usr/bin/env python3
"""Render a report from its draft(s) into self-contained HTML file(s).

Inputs (all under <site>/<slug>/):
    meta.yaml           — title, subtitle, slug, lang, langs, date, tags, status
                          Bilingual reports use suffixed keys for the secondary
                          language (e.g. title_ko, subtitle_ko).
    draft.md            — primary-language markdown with [^sNN] footnote refs
    draft.<code>.md     — additional language drafts for each code in `langs`
                          other than the primary `lang`
    working/sources.jsonl — shared across all languages

Outputs:
    <site>/<slug>/index.html          — primary language (meta.lang)
    <site>/<slug>/<code>/index.html   — each alternate language in meta.langs
"""
from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:
    yaml = None  # Fallback parser below.

from paths import REPO, add_site_arg, parse_meta_fallback, resolve_site, site_reports

TEMPLATE = REPO / "assets" / "report-template.html"


# ---------- i18n chrome ----------

I18N: dict[str, dict[str, str]] = {
    "en": {
        "brand": "Deepsearch",
        "kicker": "Deepsearch report",
        "published": "Published",
        "tags": "Tags",
        "status": "Status",
        "download": "Download HTML",
        "back": "← Back to Reports",
        "theme_label": "Toggle theme",
        "lang_other_label": "한국어",
        "lang_other_code": "ko",
        "abstract_title": "Abstract",
        "references_title": "References",
        "abstract_default": "<p><em>No abstract provided.</em></p>",
        "no_sources": '      <li><em>No sources cited.</em></li>',
        "accessed": "Accessed",
        "access_limited": "[access limited]",
        "footer_text": (
            "Report generated by the Deepsearch harness. Sources last accessed on "
            "or before {date}. Intermediate research artefacts (outline, claims, "
            "sources, critique) are preserved in the repository alongside this "
            "report."
        ),
    },
    "ko": {
        "brand": "Deepsearch",
        "kicker": "Deepsearch 리포트",
        "published": "발행일",
        "tags": "태그",
        "status": "상태",
        "download": "HTML 다운로드",
        "back": "← 리포트 목록",
        "theme_label": "테마 전환",
        "lang_other_label": "English",
        "lang_other_code": "en",
        "abstract_title": "초록",
        "references_title": "참고문헌",
        "abstract_default": "<p><em>초록이 제공되지 않았습니다.</em></p>",
        "no_sources": '      <li><em>인용된 출처가 없습니다.</em></li>',
        "accessed": "접근일",
        "access_limited": "[접근 제한]",
        "footer_text": (
            "Deepsearch 하네스로 생성된 리포트. 모든 출처는 {date} 또는 그 이전에 "
            "확인되었습니다. 중간 산출물(아웃라인, 주장, 출처, 비평)은 이 리포트와 "
            "함께 저장소에 보존됩니다."
        ),
    },
}


def chrome(lang: str) -> dict[str, str]:
    return I18N.get(lang) or I18N["en"]


# ---------- meta helpers ----------

def load_meta(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if yaml is not None:
        return yaml.safe_load(text) or {}
    return parse_meta_fallback(text)


def resolve_lang_list(meta: dict) -> tuple[str, list[str]]:
    """Return (primary_lang, langs). Backward-compatible with single-lang meta."""
    primary = str(meta.get("lang") or "en")
    declared = meta.get("langs")
    if isinstance(declared, list) and declared:
        langs = [str(l) for l in declared]
    elif isinstance(declared, str) and declared.strip():
        langs = [s.strip() for s in declared.strip("[]").split(",") if s.strip()]
    else:
        langs = [primary]
    if primary not in langs:
        langs = [primary] + langs
    return primary, langs


def resolve_field(meta: dict, key: str, lang: str, primary_lang: str) -> str:
    """Fetch `key` for the requested language.

    Primary language uses the bare key (e.g. `title`). Alternates use the
    suffixed variant (e.g. `title_ko`), falling back to the bare key if the
    translation is missing.
    """
    if lang == primary_lang:
        return str(meta.get(key) or "")
    return str(meta.get(f"{key}_{lang}") or meta.get(key) or "")


# ---------- source handling ----------

def load_sources(path: Path) -> dict[str, dict]:
    if not path.exists():
        return {}
    sources: dict[str, dict] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        sid = obj.get("id")
        if sid:
            sources[sid] = obj
    return sources


# ---------- markdown ----------

def try_markdown(text: str) -> str:
    """Try to use the `markdown` package; fall back to a minimal renderer."""
    try:
        import markdown  # type: ignore

        md = markdown.Markdown(
            extensions=["extra", "sane_lists", "smarty", "tables", "fenced_code", "toc"],
            output_format="html5",
        )
        return md.convert(text)
    except ImportError:
        return minimal_markdown(text)


INLINE_CODE = re.compile(r"`([^`]+)`")
BOLD = re.compile(r"\*\*(.+?)\*\*")
ITALIC = re.compile(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)")
LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")


def inline(s: str) -> str:
    s = html.escape(s, quote=False)
    s = INLINE_CODE.sub(lambda m: f"<code>{m.group(1)}</code>", s)
    s = BOLD.sub(lambda m: f"<strong>{m.group(1)}</strong>", s)
    s = ITALIC.sub(lambda m: f"<em>{m.group(1)}</em>", s)
    s = LINK.sub(lambda m: f'<a href="{m.group(2)}">{m.group(1)}</a>', s)
    return s


def minimal_markdown(text: str) -> str:
    lines = text.splitlines()
    out: list[str] = []
    buf: list[str] = []
    in_code = False
    code_buf: list[str] = []
    in_list = False

    def flush_para():
        nonlocal buf
        if buf:
            out.append("<p>" + inline(" ".join(buf)) + "</p>")
            buf = []

    def flush_list():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    for line in lines:
        if line.startswith("```"):
            if in_code:
                out.append("<pre><code>" + html.escape("\n".join(code_buf)) + "</code></pre>")
                code_buf = []
                in_code = False
            else:
                flush_para()
                flush_list()
                in_code = True
            continue
        if in_code:
            code_buf.append(line)
            continue
        if not line.strip():
            flush_para()
            flush_list()
            continue
        m = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m:
            flush_para()
            flush_list()
            level = len(m.group(1))
            out.append(f"<h{level}>{inline(m.group(2).strip())}</h{level}>")
            continue
        if line.lstrip().startswith(("- ", "* ")):
            flush_para()
            if not in_list:
                out.append("<ul>")
                in_list = True
            item = line.lstrip()[2:]
            out.append(f"<li>{inline(item)}</li>")
            continue
        buf.append(line.strip())
    flush_para()
    flush_list()
    return "\n".join(out)


# ---------- footnotes + abstract ----------

FOOTNOTE_RE = re.compile(r"\[\^([a-zA-Z0-9_]+)\]")


def rewrite_footnotes(html_body: str, sources: dict[str, dict]) -> tuple[str, list[str]]:
    """Replace [^sNN] with <sup><a href="#ref-N">N</a></sup>, return (html, ordered ids)."""
    order: list[str] = []

    def repl(m: re.Match[str]) -> str:
        sid = m.group(1)
        if sid not in sources:
            return m.group(0)
        if sid not in order:
            order.append(sid)
        n = order.index(sid) + 1
        return f'<sup class="footnote-ref"><a href="#ref-{n}" id="cite-{n}">[{n}]</a></sup>'

    return FOOTNOTE_RE.sub(repl, html_body), order


def split_abstract(md_body: str) -> tuple[str, str]:
    """Return (abstract_md, rest_md). Abstract is first H2 named Abstract/초록."""
    pattern = re.compile(r"^##\s+(?:Abstract|초록)\s*$", re.IGNORECASE | re.MULTILINE)
    m = pattern.search(md_body)
    if not m:
        return "", md_body
    start = m.end()
    next_h2 = re.search(r"^##\s+", md_body[start:], re.MULTILINE)
    if next_h2:
        abstract_md = md_body[start:start + next_h2.start()].strip()
        rest = md_body[:m.start()] + md_body[start + next_h2.start():]
    else:
        abstract_md = md_body[start:].strip()
        rest = md_body[:m.start()]
    return abstract_md, rest.strip()


def render_references(order: list[str], sources: dict[str, dict], strings: dict[str, str]) -> str:
    out = []
    for sid in order:
        s = sources[sid]
        authors = ", ".join(s.get("authors") or []) or "—"
        title = html.escape(s.get("title") or "(untitled)")
        venue = html.escape(s.get("venue") or "")
        year = s.get("year")
        url = s.get("url") or "#"
        accessed = s.get("accessed") or ""
        parts = [f'<span class="authors">{html.escape(authors)}</span>.']
        parts.append(f' <a href="{html.escape(url)}">{title}</a>.')
        if venue:
            parts.append(f' <span class="venue">{venue}{f", {year}" if year else ""}</span>.')
        elif year:
            parts.append(f' <span class="venue">{year}</span>.')
        if accessed:
            parts.append(f' <span class="accessed">{strings["accessed"]} {html.escape(accessed)}.</span>')
        if s.get("access_limited"):
            parts.append(f' <span class="unverified">{strings["access_limited"]}</span>')
        out.append(f'      <li id="ref-{order.index(sid) + 1}">{"".join(parts)}</li>')
    return "\n".join(out)


# ---------- path & header helpers ----------

def draft_path(report_dir: Path, lang: str, primary_lang: str) -> Path:
    """Filename convention: draft.md for primary, draft.<code>.md for others."""
    if lang == primary_lang:
        return report_dir / "draft.md"
    return report_dir / f"draft.{lang}.md"


def output_path(report_dir: Path, lang: str, primary_lang: str) -> Path:
    """<slug>/index.html for primary, <slug>/<code>/index.html for others."""
    if lang == primary_lang:
        return report_dir / "index.html"
    return report_dir / lang / "index.html"


def asset_root_for(lang: str, primary_lang: str) -> str:
    """Relative path from the report's index.html up to the site repo root."""
    return ".." if lang == primary_lang else "../.."


def index_href_for(lang: str, primary_lang: str) -> str:
    """Back-to-reports link pointing at the localized root index."""
    if lang == primary_lang:
        return "../index.html"
    return f"../../{lang}/index.html"


def brand_href_for(lang: str, primary_lang: str) -> str:
    """Header brand link: same target as the back-to-reports link (localized root)."""
    return index_href_for(lang, primary_lang)


def sibling_href_for(page_lang: str, sibling_lang: str, primary_lang: str) -> str:
    """Href from the current report page to its sibling translation."""
    if page_lang == primary_lang and sibling_lang != primary_lang:
        return f"{sibling_lang}/index.html"
    if page_lang != primary_lang and sibling_lang == primary_lang:
        return "../index.html"
    if page_lang != primary_lang and sibling_lang != primary_lang:
        return f"../{sibling_lang}/index.html"
    return "./index.html"


def build_hreflang(page_lang: str, primary_lang: str, langs: list[str]) -> str:
    if len(langs) < 2:
        return ""
    lines = []
    for l in langs:
        href = sibling_href_for(page_lang, l, primary_lang) if l != page_lang else "./index.html"
        lines.append(f'<link rel="alternate" hreflang="{html.escape(l)}" href="{html.escape(href)}">')
    # x-default points at the primary
    lines.append(
        '<link rel="alternate" hreflang="x-default" '
        f'href="{html.escape(sibling_href_for(page_lang, primary_lang, primary_lang)) if page_lang != primary_lang else "./index.html"}">'
    )
    return "\n".join(lines)


NATIVE_LANG_LABEL = {"en": "English", "ko": "한국어"}


def build_site_header(page_lang: str, primary_lang: str, langs: list[str], brand_href: str, report_is_alt: bool) -> str:
    strings = chrome(page_lang)
    # Always offer a language toggle. If the current report has a translation
    # in the alternate language, link to it; otherwise link to that language's
    # site root index. The user can always bounce out of the current report.
    alt_lang = "ko" if page_lang == "en" else "en"
    if alt_lang in langs:
        alt_href = sibling_href_for(page_lang, alt_lang, primary_lang)
    else:
        # No translation of this report; jump to the alt-language root index.
        if report_is_alt:
            # We're at <slug>/<page_lang>/index.html → three levels up? No, two.
            # <slug>/<page_lang>/index.html → site root is ../../ → then lang subdir.
            alt_href = "../../index.html" if alt_lang == "en" else f"../../{alt_lang}/index.html"
        else:
            # We're at <slug>/index.html → ../ is site root.
            alt_href = "../index.html" if alt_lang == "en" else f"../{alt_lang}/index.html"
    alt_label = NATIVE_LANG_LABEL.get(alt_lang, alt_lang)
    lang_toggle = (
        f'    <a class="site-header__lang" href="{html.escape(alt_href)}" '
        f'hreflang="{html.escape(alt_lang)}">{html.escape(alt_label)}</a>\n'
    )
    return (
        '<header class="site-header">\n'
        f'  <a class="site-header__brand" href="{html.escape(brand_href)}">{html.escape(strings["brand"])}</a>\n'
        '  <div class="site-header__controls">\n'
        f'{lang_toggle}'
        f'    <button class="site-header__theme" type="button" aria-label="{html.escape(strings["theme_label"])}" data-theme-toggle>\n'
        '      <svg class="site-header__theme-icon" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg>\n'
        '    </button>\n'
        '  </div>\n'
        '</header>'
    )


# ---------- main render ----------

def replace_template(template: str, values: dict[str, str]) -> str:
    for k, v in values.items():
        template = template.replace("{{" + k + "}}", v)
    return template


def render_one(
    report_dir: Path,
    slug: str,
    meta: dict,
    sources: dict[str, dict],
    primary_lang: str,
    langs: list[str],
    lang: str,
    template: str,
) -> Path:
    draft_p = draft_path(report_dir, lang, primary_lang)
    if not draft_p.exists():
        raise SystemExit(f"error: missing draft for lang={lang} at {draft_p}")
    draft = draft_p.read_text(encoding="utf-8")
    strings = chrome(lang)

    abstract_md, body_md = split_abstract(draft)
    abstract_html_raw = try_markdown(abstract_md) if abstract_md else strings["abstract_default"]
    body_html_raw = try_markdown(body_md)

    body_html, order = rewrite_footnotes(body_html_raw, sources)
    abstract_html, order_abs = rewrite_footnotes(abstract_html_raw, sources)
    for sid in order_abs:
        if sid not in order:
            order.append(sid)

    references_html = render_references(order, sources, strings) if order else strings["no_sources"]

    tags_raw = meta.get("tags") or []
    if isinstance(tags_raw, str):
        tags_raw = [t.strip() for t in tags_raw.strip("[]").split(",") if t.strip()]
    tags_text = ", ".join(tags_raw) if tags_raw else "—"

    title = resolve_field(meta, "title", lang, primary_lang) or slug
    subtitle = resolve_field(meta, "subtitle", lang, primary_lang)
    date_str = str(meta.get("date") or "")

    site_header = build_site_header(
        page_lang=lang,
        primary_lang=primary_lang,
        langs=langs,
        brand_href=brand_href_for(lang, primary_lang),
        report_is_alt=(lang != primary_lang),
    )
    hreflang_links = build_hreflang(lang, primary_lang, langs)

    rendered = replace_template(template, {
        "LANG": lang,
        "TITLE": html.escape(title),
        "SUBTITLE": html.escape(subtitle),
        "DESCRIPTION": html.escape(subtitle or title),
        "DATE": html.escape(date_str),
        "TAGS": html.escape(tags_text),
        "STATUS": html.escape(str(meta.get("status") or "draft")),
        "DOWNLOAD_FILENAME": html.escape(f"{slug}.html"),
        "ASSET_ROOT": asset_root_for(lang, primary_lang),
        "SITE_HEADER": site_header,
        "HREFLANG_LINKS": hreflang_links,
        "BACK_HREF": index_href_for(lang, primary_lang),
        "BACK_LABEL": html.escape(strings["back"]),
        "KICKER": html.escape(strings["kicker"]),
        "PUBLISHED_LABEL": html.escape(strings["published"]),
        "TAGS_LABEL": html.escape(strings["tags"]),
        "STATUS_LABEL": html.escape(strings["status"]),
        "DOWNLOAD_LABEL": html.escape(strings["download"]),
        "ABSTRACT_TITLE": html.escape(strings["abstract_title"]),
        "ABSTRACT_HTML": abstract_html,
        "BODY_HTML": body_html,
        "REFERENCES_TITLE": html.escape(strings["references_title"]),
        "REFERENCES_HTML": references_html,
        "FOOTER_TEXT": html.escape(strings["footer_text"].format(date=date_str or "—")),
    })

    out_path = output_path(report_dir, lang, primary_lang)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {out_path} ({len(order)} citations, lang={lang})")
    return out_path


def render_report(site: Path, slug: str) -> list[Path]:
    report_dir = site_reports(site) / slug
    if not report_dir.is_dir():
        print(f"error: {report_dir} does not exist", file=sys.stderr)
        raise SystemExit(2)

    meta = load_meta(report_dir / "meta.yaml")
    slug = str(meta.get("slug") or slug)
    primary_lang, langs = resolve_lang_list(meta)
    sources = load_sources(report_dir / "working" / "sources.jsonl")
    template = TEMPLATE.read_text(encoding="utf-8")

    outputs: list[Path] = []
    for lang in langs:
        outputs.append(render_one(report_dir, slug, meta, sources, primary_lang, langs, lang, template))
    return outputs


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("slug")
    add_site_arg(ap)
    args = ap.parse_args()
    render_report(resolve_site(args.site), args.slug)
    return 0


if __name__ == "__main__":
    sys.exit(main())
