#!/usr/bin/env python3
"""Render a report from its draft(s) into self-contained HTML file(s).

Inputs (all under <site>/<slug>/):
    meta.yaml           — title, subtitle, slug, lang, langs, date, tags, status
                          Bilingual reports use suffixed keys for the secondary
                          language (e.g. title_ko, subtitle_ko).
    draft.md            — primary-language markdown with [^sNN] footnote refs
    draft.<code>.md     — additional language drafts for each code in `langs`
                          other than the primary `lang`
    working/sources.jsonl — shared across all languages

Outputs:
    <site>/<slug>/index.html          — primary language (meta.lang)
    <site>/<slug>/<code>/index.html   — each alternate language in meta.langs
"""
from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

from common import (
    FORCE_BUILTIN,
    NATIVE_LANG_LABEL,
    draft_path,
    load_meta,
    load_sources,
    meta_tags,
    output_path,
    resolve_field,
    resolve_lang_list,
    site_header_html,
)
from paths import (
    REPO,
    add_site_arg,
    resolve_site,
    site_base_url,
    site_reports,
)

TEMPLATE = REPO / "assets" / "report-template.html"


# ---------- i18n chrome ----------

I18N: dict[str, dict[str, str]] = {
    "en": {
        "brand": "Deepsearch",
        "og_site_name": "Deepsearch",
        "github_label": "Deepsearch on GitHub",
        "kicker": "Deepsearch report",
        "published": "Published",
        "tags": "Tags",
        "status": "Status",
        "download": "Download HTML",
        "back": "← Back to Reports",
        "theme_label": "Toggle theme",
        "lang_other_label": "한국어",
        "lang_other_code": "ko",
        "abstract_title": "Abstract",
        "references_title": "References",
        "abstract_default": "<p><em>No abstract provided.</em></p>",
        "no_sources": '      <li><em>No sources cited.</em></li>',
        "accessed": "Accessed",
        "access_limited": "[access limited]",
        "footer_text": (
            "Report generated by the Deepsearch harness. Sources last accessed on "
            "or before {date}. Intermediate research artefacts (outline, claims, "
            "sources, critique) are preserved in the repository alongside this "
            "report."
        ),
    },
    "ko": {
        "brand": "Deepsearch",
        "og_site_name": "Deepsearch",
        "github_label": "GitHub에서 Deepsearch 보기",
        "kicker": "Deepsearch 리포트",
        "published": "발행일",
        "tags": "태그",
        "status": "상태",
        "download": "HTML 다운로드",
        "back": "← 리포트 목록",
        "theme_label": "테마 전환",
        "lang_other_label": "English",
        "lang_other_code": "en",
        "abstract_title": "초록",
        "references_title": "참고문헌",
        "abstract_default": "<p><em>초록이 제공되지 않았습니다.</em></p>",
        "no_sources": '      <li><em>인용된 출처가 없습니다.</em></li>',
        "accessed": "접근일",
        "access_limited": "[접근 제한]",
        "footer_text": (
            "Deepsearch 하네스로 생성된 리포트. 모든 출처는 {date} 또는 그 이전에 "
            "확인되었습니다. 중간 산출물(아웃라인, 주장, 출처, 비평)은 이 리포트와 "
            "함께 저장소에 보존됩니다."
        ),
    },
}


def chrome(lang: str) -> dict[str, str]:
    return I18N.get(lang) or I18N["en"]


# ---------- markdown ----------

def _markdown_converter():
    """Build the `markdown` converter once, or return None if unavailable.

    Constructing a ``markdown.Markdown`` costs more than converting a typical
    draft, and render-report converts twice per language (abstract + body), so
    the instance is cached and ``reset()`` between documents.
    """
    if getattr(_markdown_converter, "_cached", "unset") != "unset":
        return _markdown_converter._cached  # type: ignore[attr-defined]
    if FORCE_BUILTIN:
        _markdown_converter._cached = None  # type: ignore[attr-defined]
        return None
    try:
        import markdown  # type: ignore

        converter = markdown.Markdown(
            extensions=["extra", "sane_lists", "smarty", "tables", "fenced_code", "toc"],
            output_format="html5",
        )
    except ImportError:
        converter = None
        print(
            "warning: Python 'markdown' package not installed; using the built-in "
            "renderer. Tables, ordered/unordered lists, blockquotes and code "
            "fences are supported, but smarty / toc extensions are not. Install "
            "with `pipx install markdown` or `pip install --user markdown` for "
            "full fidelity.",
            file=sys.stderr,
        )
    _markdown_converter._cached = converter  # type: ignore[attr-defined]
    return converter


def try_markdown(text: str) -> str:
    """Convert markdown via the `markdown` package, else the built-in renderer."""
    converter = _markdown_converter()
    if converter is None:
        return minimal_markdown(text)
    converter.reset()
    return converter.convert(text)


INLINE_CODE = re.compile(r"`([^`]+)`")
BOLD = re.compile(r"\*\*(.+?)\*\*")
ITALIC = re.compile(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)")
# Underscore emphasis matters because the protocol's own qualifier markers are
# written that way — `_(vendor-stated)_`, `_(unverified — single source)_`.
# Without these the markers render as literal underscores on the built-in path.
# The word-boundary guards keep snake_case identifiers intact, which is why
# these are separate patterns rather than a character class in the ones above.
BOLD_UNDER = re.compile(r"(?<![\w_])__(?!\s)(.+?)(?<!\s)__(?![\w_])")
ITALIC_UNDER = re.compile(r"(?<![\w_])_(?!\s)(.+?)(?<!\s)_(?![\w_])")
LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")


def inline(s: str) -> str:
    s = html.escape(s, quote=False)
    s = INLINE_CODE.sub(lambda m: f"<code>{m.group(1)}</code>", s)
    s = BOLD.sub(lambda m: f"<strong>{m.group(1)}</strong>", s)
    s = BOLD_UNDER.sub(lambda m: f"<strong>{m.group(1)}</strong>", s)
    s = ITALIC.sub(lambda m: f"<em>{m.group(1)}</em>", s)
    s = ITALIC_UNDER.sub(lambda m: f"<em>{m.group(1)}</em>", s)
    s = LINK.sub(lambda m: f'<a href="{m.group(2)}">{m.group(1)}</a>', s)
    return s


TABLE_ROW_RE = re.compile(r"^\s*\|(.+)\|\s*$")
TABLE_SEP_RE = re.compile(
    r"^\s*\|?\s*:?-+:?\s*(\|\s*:?-+:?\s*)+\|?\s*$"
)
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
# Both keep the item text in group 3 so callers do not branch on which matched.
BULLET_RE = re.compile(r"^(\s*)([-*+])\s+(.*)$")
ORDERED_RE = re.compile(r"^(\s*)(\d+[.)])\s+(.*)$")
QUOTE_RE = re.compile(r"^\s*>\s?(.*)$")
HR_RE = re.compile(r"^\s*(?:-{3,}|\*{3,}|_{3,})\s*$")
SETEXT_H2_RE = re.compile(r"^\s*-{3,}\s*$")


def _split_table_row(line: str) -> list[str]:
    """Split a `| a | b | c |` row into ['a', 'b', 'c']."""
    inner = line.strip().strip("|")
    return [c.strip() for c in inner.split("|")]


def _list_match(line: str) -> re.Match[str] | None:
    return BULLET_RE.match(line) or ORDERED_RE.match(line)


def _indent_of(line: str) -> int:
    return len(line) - len(line.lstrip())


def _is_lazy_continuation(line: str) -> bool:
    """True for a plain prose line — one that does not open a new block."""
    return bool(line.strip()) and not (
        HEADING_RE.match(line)
        or HR_RE.match(line)
        or _list_match(line)
        or TABLE_ROW_RE.match(line)
        or line.startswith("```")
    )


def render_list_block(block: list[str]) -> str:
    """Render one list block, recursing for nested lists and item bodies.

    `block` is every line belonging to the list, including indented children
    and continuation lines. Items are split at the shallowest indent seen on
    the first line; deeper lines are dedented and handed back to
    ``minimal_markdown``, which turns them into the nested `<ul>`/`<ol>`.
    """
    base_indent = _indent_of(block[0])
    ordered = ORDERED_RE.match(block[0]) is not None
    items: list[list[str]] = []
    for line in block:
        m = _list_match(line)
        if m and _indent_of(line) <= base_indent:
            items.append([m.group(3)])
        elif items:
            # Child list or continuation text: strip one level of indent so the
            # recursive pass sees it as a block in its own right.
            items[-1].append(line[min(_indent_of(line), base_indent + 2):])
    tag = "ol" if ordered else "ul"
    parts = [f"<{tag}>"]
    for item in items:
        head = inline(item[0])
        body = "\n".join(item[1:])
        if body.strip():
            parts.append(f"<li>{head}\n{minimal_markdown(body)}</li>")
        else:
            parts.append(f"<li>{head}</li>")
    parts.append(f"</{tag}>")
    return "\n".join(parts)


def minimal_markdown(text: str) -> str:
    """Built-in block renderer used when the `markdown` package is absent.

    Covers what research drafts actually use: headings, paragraphs, fenced
    code, GFM tables, ordered and unordered lists (including nesting),
    blockquotes, and horizontal rules. Inline formatting is handled by
    ``inline()``.
    """
    lines = text.splitlines()
    out: list[str] = []
    buf: list[str] = []
    code_buf: list[str] = []
    in_code = False

    def flush_para():
        nonlocal buf
        if buf:
            out.append("<p>" + inline(" ".join(buf)) + "</p>")
            buf = []

    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        if line.startswith("```"):
            if in_code:
                out.append("<pre><code>" + html.escape("\n".join(code_buf)) + "</code></pre>")
                code_buf = []
                in_code = False
            else:
                flush_para()
                in_code = True
            i += 1
            continue
        if in_code:
            code_buf.append(line)
            i += 1
            continue
        if not line.strip():
            flush_para()
            i += 1
            continue
        # GFM-style table: header row + separator + 0+ body rows.
        if (
            TABLE_ROW_RE.match(line)
            and i + 1 < n
            and TABLE_SEP_RE.match(lines[i + 1])
        ):
            flush_para()
            header_cells = _split_table_row(line)
            i += 2  # consume header and separator
            body_rows: list[list[str]] = []
            while i < n and TABLE_ROW_RE.match(lines[i]):
                body_rows.append(_split_table_row(lines[i]))
                i += 1
            parts = ["<table>", "<thead><tr>"]
            for cell in header_cells:
                parts.append(f"<th>{inline(cell)}</th>")
            parts.append("</tr></thead>")
            if body_rows:
                parts.append("<tbody>")
                for row in body_rows:
                    parts.append("<tr>")
                    for cell in row:
                        parts.append(f"<td>{inline(cell)}</td>")
                    parts.append("</tr>")
                parts.append("</tbody>")
            parts.append("</table>")
            out.append("".join(parts))
            continue
        m = HEADING_RE.match(line)
        if m:
            flush_para()
            level = len(m.group(1))
            out.append(f"<h{level}>{inline(m.group(2).strip())}</h{level}>")
            i += 1
            continue
        if HR_RE.match(line):
            # `text` followed directly by `---` is a setext H2 in every
            # markdown dialect; only a standalone rule becomes an <hr>.
            if buf and SETEXT_H2_RE.match(line):
                out.append(f"<h2>{inline(' '.join(buf))}</h2>")
                buf = []
            else:
                flush_para()
                out.append("<hr>")
            i += 1
            continue
        if QUOTE_RE.match(line):
            flush_para()
            quoted: list[str] = []
            while i < n:
                qm = QUOTE_RE.match(lines[i])
                if qm:
                    quoted.append(qm.group(1))
                elif quoted and _is_lazy_continuation(lines[i]):
                    # Markdown lets a quoted paragraph run on without the `>`.
                    quoted.append(lines[i])
                else:
                    break
                i += 1
            inner = minimal_markdown("\n".join(quoted))
            out.append(f"<blockquote>\n{inner}\n</blockquote>")
            continue
        if _list_match(line):
            flush_para()
            base_indent = _indent_of(line)
            block = [line]
            i += 1
            while i < n:
                nxt = lines[i]
                if not nxt.strip():
                    # A blank line ends the list unless an indented item follows.
                    j = i + 1
                    while j < n and not lines[j].strip():
                        j += 1
                    if j < n and _indent_of(lines[j]) > base_indent and _list_match(lines[j]):
                        block.append("")
                        i += 1
                        continue
                    break
                if _list_match(nxt) or _indent_of(nxt) > base_indent:
                    block.append(nxt)
                    i += 1
                    continue
                break
            out.append(render_list_block(block))
            continue
        buf.append(line.strip())
        i += 1
    if in_code and code_buf:
        # Unterminated fence: emit what we have instead of dropping it.
        out.append("<pre><code>" + html.escape("\n".join(code_buf)) + "</code></pre>")
    flush_para()
    return "\n".join(out)


# ---------- footnotes + abstract ----------

FOOTNOTE_RE = re.compile(r"\[\^([a-zA-Z0-9_]+)\]")
ABSTRACT_HEADING_RE = re.compile(
    r"^##\s+(?:Abstract|초록)(?:\s*\((?:Abstract|초록)\))?\s*$",
    re.IGNORECASE | re.MULTILINE,
)
MANUAL_REFERENCES_HEADING_RE = re.compile(
    r"^(##|###)\s+(?:(?:\d+(?:\.\d+)*)\.?\s+)?(?:References|참고문헌)\s*$",
    re.IGNORECASE | re.MULTILINE,
)
FOOTNOTE_DEF_RE = re.compile(r"^\[\^([a-zA-Z0-9_]+)\]:\s+", re.MULTILINE)


def rewrite_footnotes(html_body: str, sources: dict[str, dict]) -> tuple[str, list[str]]:
    """Replace [^sNN] with <sup><a href="#ref-N">N</a></sup>, return (html, ordered ids)."""
    order: list[str] = []

    def repl(m: re.Match[str]) -> str:
        sid = m.group(1)
        if sid not in sources:
            return m.group(0)
        if sid not in order:
            order.append(sid)
        n = order.index(sid) + 1
        return f'<sup class="footnote-ref"><a href="#ref-{n}" id="cite-{n}">[{n}]</a></sup>'

    return FOOTNOTE_RE.sub(repl, html_body), order


def split_abstract(md_body: str) -> tuple[str, str]:
    """Return (abstract_md, rest_md). Abstract is first recognized abstract H2."""
    m = ABSTRACT_HEADING_RE.search(md_body)
    if not m:
        return "", md_body
    start = m.end()
    next_h2 = re.search(r"^##\s+", md_body[start:], re.MULTILINE)
    if next_h2:
        abstract_md = md_body[start:start + next_h2.start()].strip()
        rest = md_body[:m.start()] + md_body[start + next_h2.start():]
    else:
        abstract_md = md_body[start:].strip()
        rest = md_body[:m.start()]
    return abstract_md, rest.strip()


def strip_manual_references(md_body: str) -> str:
    """Drop a trailing manual references section from the draft body.

    Reports cite sources inline via ``[^sNN]`` and the template renders a
    normalized bibliography from ``working/sources.jsonl``. If authors leave a
    final ``## References`` / ``## 참고문헌`` section in the draft, it would
    duplicate the template-rendered bibliography.
    """
    matches = list(MANUAL_REFERENCES_HEADING_RE.finditer(md_body))
    if not matches:
        return md_body
    last = matches[-1]
    trailing = md_body[last.end():]
    if re.search(r"^##\s+", trailing, re.MULTILINE):
        return md_body
    return md_body[:last.start()].rstrip()


def strip_manual_footnote_defs(md_body: str) -> str:
    """Drop a trailing block of manual footnote definitions.

    House-style reports keep bibliography data in ``working/sources.jsonl``.
    A leftover markdown footnote-definition tail like ``[^s01]: ...`` should not
    render into the article body.
    """
    m = FOOTNOTE_DEF_RE.search(md_body)
    if not m:
        return md_body
    tail = md_body[m.start():]
    for line in tail.splitlines():
        if not line.strip():
            continue
        if FOOTNOTE_DEF_RE.match(line):
            continue
        if line.startswith("    ") or line.startswith("\t"):
            continue
        return md_body
    return md_body[:m.start()].rstrip()


def render_references(order: list[str], sources: dict[str, dict], strings: dict[str, str]) -> str:
    out = []
    for position, sid in enumerate(order, start=1):
        s = sources[sid]
        authors = ", ".join(s.get("authors") or []) or "—"
        title = html.escape(s.get("title") or "(untitled)")
        venue = html.escape(s.get("venue") or "")
        year = s.get("year")
        url = s.get("url") or "#"
        accessed = s.get("accessed") or ""
        parts = [f'<span class="authors">{html.escape(authors)}</span>.']
        parts.append(f' <a href="{html.escape(url)}">{title}</a>.')
        if venue:
            parts.append(f' <span class="venue">{venue}{f", {year}" if year else ""}</span>.')
        elif year:
            parts.append(f' <span class="venue">{year}</span>.')
        if accessed:
            parts.append(f' <span class="accessed">{strings["accessed"]} {html.escape(accessed)}.</span>')
        if s.get("access_limited"):
            parts.append(f' <span class="unverified">{strings["access_limited"]}</span>')
        out.append(f'      <li id="ref-{position}">{"".join(parts)}</li>')
    return "\n".join(out)


# ---------- path & header helpers ----------

def asset_root_for(lang: str, primary_lang: str) -> str:
    """Relative path from the report's index.html up to the site repo root."""
    return ".." if lang == primary_lang else "../.."


def index_href_for(lang: str, primary_lang: str) -> str:
    """Back-to-reports link pointing at the localized root index."""
    if lang == primary_lang:
        return "../index.html"
    return "../../index.html" if lang == "en" else f"../../{lang}/index.html"


def brand_href_for(lang: str, primary_lang: str) -> str:
    """Header brand link: same target as the back-to-reports link (localized root)."""
    return index_href_for(lang, primary_lang)


def sibling_href_for(page_lang: str, sibling_lang: str, primary_lang: str) -> str:
    """Href from the current report page to its sibling translation."""
    if page_lang == primary_lang and sibling_lang != primary_lang:
        return f"{sibling_lang}/index.html"
    if page_lang != primary_lang and sibling_lang == primary_lang:
        return "../index.html"
    if page_lang != primary_lang and sibling_lang != primary_lang:
        return f"../{sibling_lang}/index.html"
    return "./index.html"


def build_hreflang(page_lang: str, primary_lang: str, langs: list[str]) -> str:
    if len(langs) < 2:
        return ""
    lines = []
    for l in langs:
        href = sibling_href_for(page_lang, l, primary_lang) if l != page_lang else "./index.html"
        lines.append(f'<link rel="alternate" hreflang="{html.escape(l)}" href="{html.escape(href)}">')
    # x-default points at the primary
    lines.append(
        '<link rel="alternate" hreflang="x-default" '
        f'href="{html.escape(sibling_href_for(page_lang, primary_lang, primary_lang)) if page_lang != primary_lang else "./index.html"}">'
    )
    return "\n".join(lines)


def build_site_header(page_lang: str, primary_lang: str, langs: list[str], brand_href: str, report_is_alt: bool) -> str:
    strings = chrome(page_lang)
    # Always offer a language toggle. If the current report has a translation
    # in the alternate language, link to it; otherwise link to that language's
    # site root index. The user can always bounce out of the current report.
    alt_lang = "ko" if page_lang == "en" else "en"
    if alt_lang in langs:
        alt_href = sibling_href_for(page_lang, alt_lang, primary_lang)
    elif report_is_alt:
        # We're at <slug>/<page_lang>/index.html → ../../ is the site root.
        alt_href = "../../index.html" if alt_lang == "en" else f"../../{alt_lang}/index.html"
    else:
        # We're at <slug>/index.html → ../ is the site root.
        alt_href = "../index.html" if alt_lang == "en" else f"../{alt_lang}/index.html"
    return site_header_html(
        brand=strings["brand"],
        brand_href=brand_href,
        alt_lang=alt_lang,
        alt_label=NATIVE_LANG_LABEL.get(alt_lang, alt_lang),
        alt_href=alt_href,
        github_label=strings["github_label"],
        theme_label=strings["theme_label"],
    )


# ---------- main render ----------

def replace_template(template: str, values: dict[str, str]) -> str:
    for k, v in values.items():
        template = template.replace("{{" + k + "}}", v)
    return template


def render_one(
    report_dir: Path,
    slug: str,
    meta: dict,
    sources: dict[str, dict],
    primary_lang: str,
    langs: list[str],
    lang: str,
    template: str,
) -> Path:
    draft_p = draft_path(report_dir, lang, primary_lang)
    if not draft_p.exists():
        raise SystemExit(f"error: missing draft for lang={lang} at {draft_p}")
    draft = strip_manual_footnote_defs(strip_manual_references(draft_p.read_text(encoding="utf-8")))
    strings = chrome(lang)

    abstract_md, body_md = split_abstract(draft)
    abstract_html_raw = try_markdown(abstract_md) if abstract_md else strings["abstract_default"]
    body_html_raw = try_markdown(body_md)

    body_html, order = rewrite_footnotes(body_html_raw, sources)
    abstract_html, order_abs = rewrite_footnotes(abstract_html_raw, sources)
    for sid in order_abs:
        if sid not in order:
            order.append(sid)

    references_html = render_references(order, sources, strings) if order else strings["no_sources"]

    tags = meta_tags(meta)
    tags_text = ", ".join(tags) if tags else "—"

    title = resolve_field(meta, "title", lang, primary_lang) or slug
    subtitle = resolve_field(meta, "subtitle", lang, primary_lang)
    date_str = str(meta.get("date") or "")

    site_header = build_site_header(
        page_lang=lang,
        primary_lang=primary_lang,
        langs=langs,
        brand_href=brand_href_for(lang, primary_lang),
        report_is_alt=(lang != primary_lang),
    )
    hreflang_links = build_hreflang(lang, primary_lang, langs)
    canonical_url = (
        f"{site_base_url()}/{slug}/"
        if lang == primary_lang
        else f"{site_base_url()}/{slug}/{lang}/"
    )

    rendered = replace_template(template, {
        "LANG": lang,
        "TITLE": html.escape(title),
        "SUBTITLE": html.escape(subtitle),
        "DESCRIPTION": html.escape(subtitle or title),
        "CANONICAL_URL": html.escape(canonical_url),
        "OG_SITE_NAME": html.escape(strings["og_site_name"]),
        "DATE": html.escape(date_str),
        "TAGS": html.escape(tags_text),
        "STATUS": html.escape(str(meta.get("status") or "draft")),
        "DOWNLOAD_FILENAME": html.escape(f"{slug}.html"),
        "ASSET_ROOT": asset_root_for(lang, primary_lang),
        "SITE_HEADER": site_header,
        "HREFLANG_LINKS": hreflang_links,
        "BACK_HREF": index_href_for(lang, primary_lang),
        "BACK_LABEL": html.escape(strings["back"]),
        "KICKER": html.escape(strings["kicker"]),
        "PUBLISHED_LABEL": html.escape(strings["published"]),
        "TAGS_LABEL": html.escape(strings["tags"]),
        "STATUS_LABEL": html.escape(strings["status"]),
        "DOWNLOAD_LABEL": html.escape(strings["download"]),
        "ABSTRACT_TITLE": html.escape(strings["abstract_title"]),
        "ABSTRACT_HTML": abstract_html,
        "BODY_HTML": body_html,
        "REFERENCES_TITLE": html.escape(strings["references_title"]),
        "REFERENCES_HTML": references_html,
        "FOOTER_TEXT": html.escape(strings["footer_text"].format(date=date_str or "—")),
    })

    out_path = output_path(report_dir, lang, primary_lang)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {out_path} ({len(order)} citations, lang={lang})")
    return out_path


def render_report(site: Path, slug: str) -> list[Path]:
    report_dir = site_reports(site) / slug
    if not report_dir.is_dir():
        print(f"error: {report_dir} does not exist", file=sys.stderr)
        raise SystemExit(2)

    meta = load_meta(report_dir / "meta.yaml")
    slug = str(meta.get("slug") or slug)
    primary_lang, langs = resolve_lang_list(meta)
    # Parse errors are the validator's business; the renderer skips bad lines.
    sources, _ = load_sources(report_dir / "working" / "sources.jsonl")
    template = TEMPLATE.read_text(encoding="utf-8")

    outputs: list[Path] = []
    for lang in langs:
        outputs.append(render_one(report_dir, slug, meta, sources, primary_lang, langs, lang, template))
    return outputs


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("slug")
    add_site_arg(ap)
    args = ap.parse_args()
    render_report(resolve_site(args.site), args.slug)
    return 0


if __name__ == "__main__":
    sys.exit(main())
