#!/usr/bin/env python3
"""Regenerate the site repo's root index.html by scanning <site>/*/meta.yaml.

Only reports whose meta.yaml `status` is `ready` or `published` are listed.
Draft reports are skipped. Sorted by `date` descending, then by slug.

The site repo location is resolved via ``paths.resolve_site`` (CLI ``--site``,
``DEEPSEARCH_SITE`` env, or the default ``../reports``). Report directories
sit flat at the site repo root alongside ``index.html`` and ``assets/``;
non-report entries (missing ``meta.yaml``) are ignored.
"""
from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:
    yaml = None

from paths import add_site_arg, parse_meta_fallback, resolve_site, site_reports


def parse_meta(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if yaml is not None:
        try:
            return yaml.safe_load(text) or {}
        except Exception:
            return {}
    return parse_meta_fallback(text)


def collect(reports_dir: Path) -> list[dict]:
    entries = []
    if not reports_dir.is_dir():
        return entries
    for child in reports_dir.iterdir():
        meta_path = child / "meta.yaml"
        index_path = child / "index.html"
        if not (child.is_dir() and meta_path.exists() and index_path.exists()):
            continue
        meta = parse_meta(meta_path)
        status = str(meta.get("status") or "").lower()
        if status not in ("ready", "published"):
            continue
        meta["slug"] = meta.get("slug") or child.name
        meta["href"] = f"{child.name}/"
        entries.append(meta)
    entries.sort(key=lambda m: (str(m.get("date") or ""), m["slug"]), reverse=True)
    return entries


TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Deepsearch — Reports</title>
<meta name="description" content="Deep research reports generated by the Deepsearch harness.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Noto+Sans+KR:wght@400;500;600;700&family=Noto+Sans+Mono:wght@400;500;600;700&display=swap">
<link rel="stylesheet" href="assets/style.css">
</head>
<body>
<article class="page">
  <header class="masthead">
    <div class="kicker">Deepsearch</div>
    <h1>Reports</h1>
    <p class="subtitle">A collection of deep-research reports — one topic at a time, sources preserved.</p>
    <div class="meta">
      <span><strong>{{COUNT}}</strong> reports</span>
      <span><strong>Updated</strong> {{UPDATED}}</span>
    </div>
  </header>

  <main>
    <ul class="index-list">
{{ITEMS}}
    </ul>
  </main>
</article>
<footer class="site-footer">
  <span>Deepsearch harness</span>
  <span>Published via GitHub Pages</span>
</footer>
</body>
</html>
"""


def render_item(m: dict) -> str:
    title = html.escape(str(m.get("title") or m["slug"]))
    subtitle = html.escape(str(m.get("subtitle") or ""))
    date = html.escape(str(m.get("date") or ""))
    tags = m.get("tags") or []
    if isinstance(tags, str):
        tags = [t.strip() for t in re.split(r"[,\s]+", tags) if t.strip()]
    tag_txt = " · ".join(html.escape(t) for t in tags) if tags else ""
    href = html.escape(m["href"])
    parts = [
        '      <li>',
        f'        <div class="entry-date">{date}</div>' if date else "",
        f'        <p class="entry-title"><a href="{href}">{title}</a></p>',
    ]
    if subtitle:
        parts.append(f'        <p class="entry-subtitle">{subtitle}</p>')
    if tag_txt:
        parts.append(f'        <div class="entry-tags">{tag_txt}</div>')
    parts.append('      </li>')
    return "\n".join(p for p in parts if p)


def render_index(site: Path) -> Path:
    reports_dir = site_reports(site)
    out_path = site / "index.html"
    entries = collect(reports_dir)
    items_html = "\n".join(render_item(m) for m in entries) or '      <li><em>No reports published yet.</em></li>'
    updated = entries[0].get("date") if entries else "—"
    out = (
        TEMPLATE
        .replace("{{COUNT}}", str(len(entries)))
        .replace("{{UPDATED}}", html.escape(str(updated)))
        .replace("{{ITEMS}}", items_html)
    )
    out_path.write_text(out, encoding="utf-8")
    print(f"wrote {out_path} ({len(entries)} entries)")
    return out_path


def main() -> int:
    ap = argparse.ArgumentParser()
    add_site_arg(ap)
    args = ap.parse_args()
    render_index(resolve_site(args.site))
    return 0


if __name__ == "__main__":
    sys.exit(main())
